[package]
name = "micro-matrix-bot"
version = "0.1.0"
authors = ["Luke Petrolekas <reclarion@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
